services:
  db:
    image: postgres:14
    container_name: smart_estate_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: smartestatedb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy 
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: smart_estate_backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: smartestatedb
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=smartestatedb;Username=postgres;Password=123"
      APPLY_MIGRATIONS: "true"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart_estate_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pg_data:
