version: '3.8'

services:
  db:
    image: postgres:14
    container_name: smart_estate_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    restart: always

volumes:
  pg_data: