CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Developers" (
    "DeveloperId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Website" text,
    "BuildingsCount" integer NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Developers" PRIMARY KEY ("DeveloperId")
);

CREATE TABLE "InfrastructureInfos" (
    "InfrastructureInfoId" integer GENERATED BY DEFAULT AS IDENTITY,
    "MinutesToShop" integer,
    "MinutesToMetro" integer,
    "MinutesToSchool" integer,
    "MinutesToKindergarten" integer,
    "MinutesToBusStop" integer,
    "MinutesToPharmacy" integer,
    "Facilities" text NOT NULL,
    CONSTRAINT "PK_InfrastructureInfos" PRIMARY KEY ("InfrastructureInfoId")
);

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Login" text NOT NULL,
    "HashedPassword" text NOT NULL,
    "Email" text,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE TABLE "Buildings" (
    "BuildingId" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeveloperId" integer NOT NULL,
    "ConstructionStatus" text NOT NULL,
    "FloorCount" integer NOT NULL,
    "Address" text NOT NULL,
    "InfrastructureInfoId" integer,
    CONSTRAINT "PK_Buildings" PRIMARY KEY ("BuildingId"),
    CONSTRAINT "FK_Buildings_Developers_DeveloperId" FOREIGN KEY ("DeveloperId") REFERENCES "Developers" ("DeveloperId") ON DELETE CASCADE,
    CONSTRAINT "FK_Buildings_InfrastructureInfos_InfrastructureInfoId" FOREIGN KEY ("InfrastructureInfoId") REFERENCES "InfrastructureInfos" ("InfrastructureInfoId")
);

CREATE TABLE "Flats" (
    "FlatId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Layout" text,
    "Square" numeric NOT NULL,
    "Roominess" integer NOT NULL,
    "Floor" integer NOT NULL,
    "CianLink" text NOT NULL,
    "BuildingId" integer NOT NULL,
    "FinishType" text NOT NULL,
    CONSTRAINT "PK_Flats" PRIMARY KEY ("FlatId"),
    CONSTRAINT "FK_Flats_Buildings_BuildingId" FOREIGN KEY ("BuildingId") REFERENCES "Buildings" ("BuildingId") ON DELETE CASCADE
);

CREATE TABLE "PriceHistories" (
    "PriceHistoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "FlatId" integer NOT NULL,
    "Price" numeric NOT NULL,
    "ChangeDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PriceHistories" PRIMARY KEY ("PriceHistoryId"),
    CONSTRAINT "FK_PriceHistories_Flats_FlatId" FOREIGN KEY ("FlatId") REFERENCES "Flats" ("FlatId") ON DELETE CASCADE
);

CREATE TABLE "UserComparisons" (
    "CompareId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FlatId1" integer NOT NULL,
    "FlatId2" integer NOT NULL,
    CONSTRAINT "PK_UserComparisons" PRIMARY KEY ("CompareId"),
    CONSTRAINT "FK_UserComparisons_Flats_FlatId1" FOREIGN KEY ("FlatId1") REFERENCES "Flats" ("FlatId"),
    CONSTRAINT "FK_UserComparisons_Flats_FlatId2" FOREIGN KEY ("FlatId2") REFERENCES "Flats" ("FlatId"),
    CONSTRAINT "FK_UserComparisons_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "UserFavorites" (
    "FavoriteId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FlatId" integer NOT NULL,
    CONSTRAINT "PK_UserFavorites" PRIMARY KEY ("FavoriteId"),
    CONSTRAINT "FK_UserFavorites_Flats_FlatId" FOREIGN KEY ("FlatId") REFERENCES "Flats" ("FlatId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserFavorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_Buildings_DeveloperId" ON "Buildings" ("DeveloperId");

CREATE UNIQUE INDEX "IX_Buildings_InfrastructureInfoId" ON "Buildings" ("InfrastructureInfoId");

CREATE INDEX "IX_Flats_BuildingId" ON "Flats" ("BuildingId");

CREATE INDEX "IX_PriceHistories_FlatId" ON "PriceHistories" ("FlatId");

CREATE INDEX "IX_UserComparisons_FlatId1" ON "UserComparisons" ("FlatId1");

CREATE INDEX "IX_UserComparisons_FlatId2" ON "UserComparisons" ("FlatId2");

CREATE INDEX "IX_UserComparisons_UserId" ON "UserComparisons" ("UserId");

CREATE INDEX "IX_UserFavorites_FlatId" ON "UserFavorites" ("FlatId");

CREATE INDEX "IX_UserFavorites_UserId" ON "UserFavorites" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250328213401_Initial', '9.0.3');

COMMIT;

