import psycopg2
from psycopg2 import sql
from psycopg2.extras import execute_batch

def save_to_postgresql(stations, db_params):
    """Сохраняет данные станций в PostgreSQL."""
    conn = None
    try:
        conn = psycopg2.connect(**db_params)
        cursor = conn.cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS "Metro" (
                "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" TEXT NOT NULL UNIQUE,
                "Latitude" DOUBLE PRECISION NOT NULL,
                "Longitude" DOUBLE PRECISION NOT NULL
            )
        """)

        insert_query = sql.SQL("""
            INSERT INTO "Metro" ("Name", "Latitude", "Longitude")
            VALUES (%s, %s, %s)
            ON CONFLICT ("Name") DO NOTHING
        """)

        for station in stations:
            try:
                data = [(s['metro_station'], s['latitude'], s['longitude']) for s in stations]
                execute_batch(cursor, insert_query, data)
            except KeyError as e:
                print(f"Ошибка в данных станции: {station}. Пропуск. Ошибка: {e}")
                continue


        conn.commit()
        print(f"Успешно обработано {len(stations)} станций")
        return True

    except Exception as e:
        print(f"Ошибка при сохранении в PostgreSQL: {e}")
        if conn:
            conn.rollback()
        return False
    finally:
        if conn:
            conn.close()