import psycopg2
from psycopg2 import sql


def save_to_postgresql(developers, db_params):
    """Сохраняет данные в PostgreSQL."""
    try:
        conn = psycopg2.connect(**db_params)
        cursor = conn.cursor()

        create_table_query = """
            CREATE TABLE IF NOT EXISTS "Developers" (
                "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" TEXT NOT NULL,
                "Website" TEXT,
                "BuildingsCount" TEXT 
            )
        """
        cursor.execute(create_table_query)

        cursor.execute('TRUNCATE TABLE public."Developers" RESTART IDENTITY CASCADE')

        insert_query = sql.SQL("""
        INSERT INTO "Developers" ("Name", "Website", "BuildingsCount")
        VALUES (%s, %s, %s)
        """)

        for developer in developers:
            cursor.execute(insert_query, (
                developer['name'],
                developer['website'],
                developer['buildings']
            ))

        conn.commit()
        print(f"Успешно сохранено {len(developers)} станций в БД PostgreSQL")
        return True

    except Exception as e:
        print(f"Ошибка при сохранении в PostgreSQL: {e}")
        return False
    finally:
        if conn:
            conn.close()