import psycopg2
from psycopg2 import sql


def save_to_postgresql(stations, db_params):
    """Сохраняет данные станций в PostgreSQL."""
    try:
        conn = psycopg2.connect(**db_params)
        cursor = conn.cursor()

        create_table_query = """
            CREATE TABLE IF NOT EXISTS "Metro" (
                "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" TEXT NOT NULL,
                "Latitude" DOUBLE PRECISION NOT NULL,
                "Longitude" DOUBLE PRECISION NOT NULL
            )
        """
        cursor.execute(create_table_query)

        cursor.execute('TRUNCATE TABLE public."Metro" RESTART IDENTITY CASCADE')

        insert_query = sql.SQL("""
        INSERT INTO "Metro" ("Name", "Latitude", "Longitude")
        VALUES (%s, %s, %s)
        """)

        for station in stations:
            cursor.execute(insert_query, (
                station['metro_station'],
                station['latitude'],
                station['longitude']
            ))

        conn.commit()
        print(f"Успешно сохранено {len(stations)} станций в БД PostgreSQL")
        return True

    except Exception as e:
        print(f"Ошибка при сохранении в PostgreSQL: {e}")
        return False
    finally:
        if conn:
            conn.close()